services:
  - type: web
    name: calorie-counter
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn calorie_counter_project.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://calorie_project_user:TBSkdh2HNVTgiEF4nd1pguctFSkThtEO@dpg-d8a2angg4nts73d3rveg-a/calorie_project
      - key: PYTHON_VERSION
        value: 3.10.13