# Generated by Django 6.0.5 on 2026-05-24 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.PositiveIntegerField(help_text='Calories in kcal')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
